# KeyError
# Ocorre quando tentamos acessar um dicionário com uma chave que não existe

"""
    dic = {"python": "university"}
    print(dic["geek"])
    """
